package com.jf.baselibraray.net;

public interface ParaKeys {

    String DIALOG_IGNORE_VISIBLE = "DIALOG_IGNORE_VISIBLE";
    String DIALOG_ISCLOSEMAIN = "DIALOG_ISCLOSEMAIN";
    String DIALOG_CANCELABLE = "DIALOG_CANCELABLE";
    String DIALOG_AUTHORIGHT_NEED = "DIALOG_AUTHORIGHT_NEED";
    String DIALOG_AUTHORIGHT_MSG = "DIALOG_AUTHORIGHT_MSG";
    String DIALOG_AUTHORIGHT_TITLE = "DIALOG_AUTHORIGHT_TITLE";
    String DIALOG_IGNORE_TXT = "DIALOG_IGNORE_TXT";
    String DIALOG_CONFIRM_TXT = "DIALOG_CONFIRM_TXT";
    String DIALOG_AUTHORIGHT_JUMP = "DIALOG_AUTHORIGHT_JUMP";
    String DIALOG_AUTHORIGHT_TAG = "DIALOG_AUTHORIGHT_TAG";

    String EXTRA_STRING = "EXTRA_STRING";
    String EXTRA_ID = "EXTRA_ID";

}
