package com.haozi.greendaolib;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.haozi.greendaolib.SmsOrginEntity;

import com.haozi.greendaolib.SmsOrginEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig smsOrginEntityDaoConfig;

    private final SmsOrginEntityDao smsOrginEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        smsOrginEntityDaoConfig = daoConfigMap.get(SmsOrginEntityDao.class).clone();
        smsOrginEntityDaoConfig.initIdentityScope(type);

        smsOrginEntityDao = new SmsOrginEntityDao(smsOrginEntityDaoConfig, this);

        registerDao(SmsOrginEntity.class, smsOrginEntityDao);
    }
    
    public void clear() {
        smsOrginEntityDaoConfig.clearIdentityScope();
    }

    public SmsOrginEntityDao getSmsOrginEntityDao() {
        return smsOrginEntityDao;
    }

}
